class Nmaahcmm < Formula
  desc "Scripts for running NMAAHC microservices"
  homepage "https://github.com/NMAAHC/nmaahcmm"
  url "https://github.com/NMAAHC/nmaahcmm/archive/refs/tags/nmaahcmm-v0.1.tar.gz"
  sha256 "fd4e7ba81005bbe0ac0f67701f80f773b3e95fd2bba5565d54bda490c2d9dbbc"
  head "https://github.com/NMAAHC/nmaahcmm.git", branch: "main"
  license ""

  depends_on "cowsay"
  depends_on "exiftool"
  depends_on "ffmpeg"
  depends_on "md5deep"
  depends_on "media-info"
  depends_on "mediaconch"
  depends_on "mkvtoolnix"
  depends_on "rsync"
  depends_on "tree"
  depends_on "xmlstarlet"

  def install
    bin.install "diffFrameMD5"
    bin.install "getduration"
    bin.install "gm.conf"
    bin.install "gmconfig"
    bin.install "ingestfile"
    bin.install "makechecksum"
    bin.install "makeconcat"
    bin.install "makeDer"
    bin.install "makedrivetree"
    bin.install "makeframemd5"
    bin.install "makegm"
    bin.install "makeH264"
    bin.install "makemediainfo"
    bin.install "makemetadata"
    bin.install "moveDPX"
    bin.install "nmaahcmmconfig"
    bin.install "nmaahcmmfunctions"
    bin.install "removeDSStore"
    bin.install "rename"
    bin.install "restructureDPX"
    bin.install "restructureForVFCU"
    bin.install "restructureSIP"
    bin.install "verifySIP"
  end
end
