class Nmaahcmm < Formula
  desc "Scripts for running NMAAHC microservices"
  homepage "https://github.com/NMAAHC/nmaahcmm"
  url "https://github.com/NMAAHC/nmaahcmm/archive/refs/tags/nmaahcmm-v0.0.8.tar.gz"
  sha256 "5b62c7aab546e3d653af1894d810e084381b13ddfadedd8294de7d38bf45ebff"
  head "https://github.com/NMAAHC/nmaahcmm.git", branch: "main"
  license ""

  depends_on "cowsay"
  depends_on "exiftool"
  depends_on "ffmpeg"
  depends_on "md5deep"
  depends_on "media-info"
  depends_on "mediaconch"
  depends_on "mkvtoolnix"
  depends_on "rsync"
  depends_on "tree"
  depends_on "xmlstarlet"

  def install
    bin.install "camera_cards"
    bin.install "diffFrameMD5"
    bin.install "getduration"
    bin.install "gm.conf"
    bin.install "gmconfig"
    bin.install "ingestfile"
    bin.install "makechecksum"
    bin.install "makeconcat"
    bin.install "makeDer"
    bin.install "makedrivetree"
    bin.install "makeframemd5"
    bin.install "makegm"
    bin.install "makeH264"
    bin.install "makemediainfo"
    bin.install "makemetadata"
    bin.install "mkvnote"
    bin.install "moveDPX"
    bin.install "nmaahcmmconfig"
    bin.install "nmaahcmmfunctions"
    bin.install "removeDSStore"
    bin.install "rename"
    bin.install "restructureDPX"
    bin.install "restructureForVFCU"
    bin.install "restructureSIP"
    bin.install "verifySIP"
  end
end
